Description: A stack containing resources for an AWS Serverless Lambda function deployed through an AWS ECR. 

Resources:
  primer: 
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: mlops-inference2
        Code: 
          ImageUri: 891377264944.dkr.ecr.us-east-2.amazonaws.com/mlops:latest
        PackageType: Image
        Role: arn:aws:iam::891377264944:role/tim-course-mlops
